steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/carbon-track-499403/carbon-track'
    - '.'

images:
- 'gcr.io/carbon-track-499403/carbon-track'

options:
  logging: CLOUD_LOGGING_ONLY
 
 
